dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  # - '3.8' # Tensorflow currently compatible up to 3.7
install:
  - pip install -e .
  - pip install pytest pytest-cov
  - pip install codecov
script:
  - pytest --cov=./deepquest/
after_success:
  - codecov
