dist: xenial
language: python
python:
  # - '3.6'
  - '3.7'
  # - '3.8'
env:
    - TEST_LEVEL=sentence
    - TEST_LEVEL=document
    - TEST_LEVEL=word

install:
  - pip install -e .
  - pip install pytest
script:
  - pytest
