sudo: required
dist: xenial
language: python
python:
  - '3.7'
env:
    - KERAS_BACKEND=theano TEST_MODE=sentence
    - KERAS_BACKEND=theano TEST_MODE=document
    - KERAS_BACKEND=tensorflow TEST_MODE=sentence
    - KERAS_BACKEND=tensorflow TEST_MODE=document

# command to install dependencies
install:
  # code below is taken from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install dependencies with conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file req-travis-conda.txt
  - source activate test-environment # will need 'source activate' for conda v<4.6
  - conda install mkl mkl-service
  - pip install -r req-travis-pip.txt
  - export PYTHONPATH=$PWD:$PWD/src:$PYTHONPATH

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH

  # install TensorFlow (CPU version).
  - pip install tensorflow==1.13.2 # TF v 1.13.2 is the currently tested version of tf with deepquest

    # detect whether core files are changed or not (from Keras)
  - export CORE_CHANGED=False;
  - export APP_CHANGED=False;

  # Install Theano-1.0.4 (for compatibility with numpy>=1.16
  - conda install -c conda-forge theano

# command to run tests
script:
  - utils/test-master.sh
