dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
env:
    - TEST_MODE=sentence
    - TEST_MODE=document
    - TEST_MODE=word

install:
  - pip install -e .

script:
  - KERAS_BACKEND=tensorflow tests/test-master.sh
