N_GPUS: 2

# Input data params
TASK_NAME: 'testData-sent'                         # Task name
SRC_LAN: 'src'                                     # Language of the source text
TRG_LAN: 'mt'                                      # Language of the target text
# SRC_LAN or TRG_LAN are expected to be the file extensions of the data files

SEED: 1                                            # Value to set seed for deterministic results. (omit for random results)

OUTPUTS_IDS_DATASET: ['sent_qe']
OUTPUTS_IDS_MODEL: ['sent_qe']

# Dataset class parameters
PRED_SCORE: 'hter'                                  # used as file extension of the score files
OUT_ACTIVATION: 'sigmoid'                           #set as ‘relu’ function if predicted scores are in (0, +infinity), as a ‘sigmoid’ function for scores in (0,1) (for example, BLEU or HTER), or as a linear’ function for scores in (-infinity, +infinity).

# Evaluation params
METRICS: ['qe_metrics']                             # Metric used for evaluating the model
EVAL_ON_SETS: ['val']                               # Possible values: 'train', 'val' and 'test' (external evaluator)
NO_REF: False                                       # True if there is no reference data

MAX_INPUT_TEXT_LEN: 70                              # Maximum length of the input sequence

MAX_OUTPUT_TEXT_LEN: 70                             # Maximum length of the output sequence
                                                    # set to 0 if we want to use the whole answer as a single class

PATIENCE: 5                                         # We'll stop if the val STOP_METRIC does not improve after this number of evaluations
BATCH_SIZE: 50                                      # Size of each minibatch

STOP_METRIC: 'pearson'                              # Metric for the stop

# Model parameters
MODEL_TYPE: 'EncSent'                               # Model to train.
